# Generated by Django 5.2.10 on 2026-01-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mappings', models.JSONField(default=dict)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=255)),
                ('transformed_file_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('marketplace_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplacetempate')),
                ('seller_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerfiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
