EVALUATION_STATUS_PENDING = "pending"
EVALUATION_STATUS_FAILED = "failed"
EVALUATION_STATUS_SUCCESS = "success"

EVALUATION_STATUS_CHOICES = (
    (EVALUATION_STATUS_PENDING, "Pending"),
    (EVALUATION_STATUS_FAILED, "Failed"),
    (EVALUATION_STATUS_SUCCESS, "Success"),
)

TRANSFORMED_FOLDER = "transformed"
