# Generated by Django 5.2.10 on 2026-01-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='bucket_name',
            new_name='seller_uuid',
        ),
        migrations.RenameField(
            model_name='sellerfiles',
            old_name='type',
            new_name='file_type',
        ),
    ]
